package inspect

import (
	"os"
	"path/filepath"
	"testing"
)

// The fixtures are real pickles of a __reduce__ returning os.system, one per
// protocol, generated by CPython. Regenerate with:
//
//	python3 -c 'import pickle,os
//	class E:
//	    def __reduce__(self): return (os.system, ("echo pwned",))
//	[open(f"internal/inspector/testdata/evil_proto{p}.pkl","wb").write(
//	    pickle.dumps(E(), protocol=p)) for p in range(6)]'

// Every pickle protocol must reach the Critical finding.
//
// This exists because protocols 4 and 5 originally did not. GLOBAL writes the
// import inline as "module\nattr\n", but STACK_GLOBAL pushes module and attr
// as separate length-prefixed strings, so a byte search for the inline form
// finds nothing and the stream degrades to a generic "risky opcodes" warning.
// Python's DEFAULT_PROTOCOL is 5, so that gap covered the ordinary case: a
// plain pickle.dumps of a malicious payload.
func TestDangerousImportDetectedInEveryPickleProtocol(t *testing.T) {
	for _, proto := range []string{"0", "1", "2", "3", "4", "5"} {
		t.Run("protocol"+proto, func(t *testing.T) {
			dir := t.TempDir()
			src := filepath.Join("testdata", "evil_proto"+proto+".pkl")
			raw, err := os.ReadFile(src)
			if err != nil {
				t.Fatalf("read fixture: %v", err)
			}
			// Named like real weights so the pickle path is taken.
			if err := os.WriteFile(filepath.Join(dir, "pytorch_model.bin"), raw, 0o644); err != nil {
				t.Fatal(err)
			}

			report, err := Inspect(dir, DefaultLimits())
			if err != nil {
				t.Fatalf("Inspect: %v", err)
			}

			var critical bool
			var got []string
			for _, f := range report.Findings {
				got = append(got, f.ID+"("+f.Severity+")")
				if f.ID == "TESS-PICKLE-001" && f.Severity == "Critical" {
					critical = true
				}
			}
			if !critical {
				t.Fatalf("protocol %s: os.system not reported as Critical; got %v", proto, got)
			}
		})
	}
}

// The STACK_GLOBAL match requires the opcode plus both operands as
// length-prefixed strings. A document that merely contains the words must not
// be reported as executing code, or the detection becomes noise.
func TestBenignPickleMentioningModuleNamesIsNotCritical(t *testing.T) {
	dir := t.TempDir()
	raw, err := os.ReadFile(filepath.Join("testdata", "benign_words.pkl"))
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	if err := os.WriteFile(filepath.Join(dir, "pytorch_model.bin"), raw, 0o644); err != nil {
		t.Fatal(err)
	}

	report, err := Inspect(dir, DefaultLimits())
	if err != nil {
		t.Fatalf("Inspect: %v", err)
	}

	for _, f := range report.Findings {
		if f.ID == "TESS-PICKLE-001" {
			t.Fatalf("benign pickle reported as importing a dangerous callable: %s", f.Description)
		}
	}
}

func TestReferencesImportMatchesBothEncodings(t *testing.T) {
	// GLOBAL form, protocols 0-3.
	if !referencesImport([]byte("c posix\nsystem\n"), "posix", "system") {
		t.Error("GLOBAL encoding not matched")
	}
	// STACK_GLOBAL form: SHORT_BINUNICODE operands plus the 0x93 opcode.
	stack := []byte{opShortBinUnicode, 5, 'p', 'o', 's', 'i', 'x',
		opShortBinUnicode, 6, 's', 'y', 's', 't', 'e', 'm', opStackGlobal}
	if !referencesImport(stack, "posix", "system") {
		t.Error("STACK_GLOBAL encoding not matched")
	}
	// Operands present but no STACK_GLOBAL opcode: not an import.
	noOp := []byte{opShortBinUnicode, 5, 'p', 'o', 's', 'i', 'x',
		opShortBinUnicode, 6, 's', 'y', 's', 't', 'e', 'm'}
	if referencesImport(noOp, "posix", "system") {
		t.Error("matched without a STACK_GLOBAL opcode")
	}
}
